
package so2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyHelloImplService", targetNamespace = "http://so2/", wsdlLocation = "http://localhost:7070/WebServiceSO2/myhello?WSDL")
public class MyHelloImplService
    extends Service
{

    private final static URL MYHELLOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYHELLOIMPLSERVICE_EXCEPTION;
    private final static QName MYHELLOIMPLSERVICE_QNAME = new QName("http://so2/", "MyHelloImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7070/WebServiceSO2/myhello?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYHELLOIMPLSERVICE_WSDL_LOCATION = url;
        MYHELLOIMPLSERVICE_EXCEPTION = e;
    }

    public MyHelloImplService() {
        super(__getWsdlLocation(), MYHELLOIMPLSERVICE_QNAME);
    }

    public MyHelloImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYHELLOIMPLSERVICE_QNAME, features);
    }

    public MyHelloImplService(URL wsdlLocation) {
        super(wsdlLocation, MYHELLOIMPLSERVICE_QNAME);
    }

    public MyHelloImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYHELLOIMPLSERVICE_QNAME, features);
    }

    public MyHelloImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyHelloImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyHelloImpl
     */
    @WebEndpoint(name = "MyHelloImplPort")
    public MyHelloImpl getMyHelloImplPort() {
        return super.getPort(new QName("http://so2/", "MyHelloImplPort"), MyHelloImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyHelloImpl
     */
    @WebEndpoint(name = "MyHelloImplPort")
    public MyHelloImpl getMyHelloImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://so2/", "MyHelloImplPort"), MyHelloImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYHELLOIMPLSERVICE_EXCEPTION!= null) {
            throw MYHELLOIMPLSERVICE_EXCEPTION;
        }
        return MYHELLOIMPLSERVICE_WSDL_LOCATION;
    }

}
